package com.leihou.interview.mapper;

import com.leihou.interview.entity.HmUser;
import com.leihou.interview.entity.HmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    long countByExample(HmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int deleteByExample(HmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int insert(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int insertSelective(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    List<HmUser> selectByExample(HmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    HmUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") HmUser record, @Param("example") HmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int updateByExample(@Param("record") HmUser record, @Param("example") HmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int updateByPrimaryKeySelective(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    int updateByPrimaryKey(HmUser record);
}