package com.leihou.interview.entity;

import java.util.Date;

public class HmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.id
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.username
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.loginid
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.password
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.mobile
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.email
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.avatar
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.create_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.last_update_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.last_login_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.security_level
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private Long securityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.type
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    private Long type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.id
     *
     * @return the value of hm_user.id
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.id
     *
     * @param id the value for hm_user.id
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.username
     *
     * @return the value of hm_user.username
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.username
     *
     * @param username the value for hm_user.username
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.loginid
     *
     * @return the value of hm_user.loginid
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.loginid
     *
     * @param loginid the value for hm_user.loginid
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.password
     *
     * @return the value of hm_user.password
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.password
     *
     * @param password the value for hm_user.password
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.mobile
     *
     * @return the value of hm_user.mobile
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.mobile
     *
     * @param mobile the value for hm_user.mobile
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.email
     *
     * @return the value of hm_user.email
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.email
     *
     * @param email the value for hm_user.email
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.avatar
     *
     * @return the value of hm_user.avatar
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.avatar
     *
     * @param avatar the value for hm_user.avatar
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.create_time
     *
     * @return the value of hm_user.create_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.create_time
     *
     * @param createTime the value for hm_user.create_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.last_update_time
     *
     * @return the value of hm_user.last_update_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.last_update_time
     *
     * @param lastUpdateTime the value for hm_user.last_update_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.last_login_time
     *
     * @return the value of hm_user.last_login_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.last_login_time
     *
     * @param lastLoginTime the value for hm_user.last_login_time
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.security_level
     *
     * @return the value of hm_user.security_level
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public Long getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.security_level
     *
     * @param securityLevel the value for hm_user.security_level
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setSecurityLevel(Long securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.type
     *
     * @return the value of hm_user.type
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.type
     *
     * @param type the value for hm_user.type
     *
     * @mbg.generated Thu Aug 16 15:01:19 CST 2018
     */
    public void setType(Long type) {
        this.type = type;
    }
}